baseurl = "www.ramjeeganti.com/"
languageCode = "en-us"
title = "rAmg"
disqus_shortname = "unknownunknown"

[permalinks]
    post = "blog/:year/:month/:day/:title/"

[params]
    facebook = "gantir"
    twitter = "gantir"
    linkedin = "gantir"
    github = "gantir"
    gplus = "113134532290747889683"
    description = "personal webspace of Ramjee Ganti"
    email = "site@ramjeeganti.com"
    ga = "UA-893783-6"
    hostname = "www.ramjeeganti.com"
    comments = true

[author]
    name = "Ramjee Ganti"
    image = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAOAAAAAJGE5MGE5Y2FjLTdkZTEtNGRiNS04NzI0LTkwYWFiNTgwZWE4Yw.jpg"
    description = " a son, a husband, a father trying to eke out unique corner in this world."
